version: '3'

services:
    ngspice:
        build: 
            context: .
        volumes:
            -   ~/ngspice_data:/tmp
        environment:
            - LOGIN_PW=passwd
        ports:
            - 3000:3000
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
